#!/usr/bin/env python3
# Copyright 2026 InsightOS
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy at https://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND.
# See the License for the specific language governing permissions and limitations.

"""Generate the standalone English bootstrap from the canonical installer sources.

Only Python string tokens are translated; comments, expressions and user data
are not processed at runtime. The embedded management modules run only after
the original archive passes checksum and safe-extraction checks. They live
outside the immutable payload and are persisted as the instance management CLI.
No extra download or rebuilt business artifact is required.
"""
import argparse
import ast
import io
import json
from pathlib import Path
import re
import tokenize

HERE = Path(__file__).resolve().parent
CJK = re.compile('[\u4e00-\u9fff]')


def translate(source):
    catalog = json.loads((HERE/'installer.en.json').read_text())
    pattern = re.compile('|'.join(re.escape(k) for k in sorted(catalog, key=len, reverse=True)))
    tokens = []
    for token in tokenize.generate_tokens(io.StringIO(source).readline):
        if token.type == tokenize.STRING or tokenize.tok_name[token.type] == 'FSTRING_MIDDLE':
            value = pattern.sub(lambda match: catalog[match[0]], token.string)
            if CJK.search(value):
                raise ValueError('Missing English translation: '+repr(token.string))
            token = token._replace(string=value)
        tokens.append(token)
    result = tokenize.untokenize(tokens)
    ast.parse(result)
    return result


def replace_once(source, old, new):
    if source.count(old) != 1:
        raise ValueError('Canonical installer changed; review English integration: '+old)
    return source.replace(old, new, 1)


def manager_sources():
    result = {name: translate((HERE/'runtime'/name).read_text())
              for name in ('installer.py', 'install_support.py', 'uninstall.py')}
    # English management code is independent of immutable business payloads.
    # Assets still come from the verified archive, while future semanticctl calls
    # retain the English management modules that installed/configured the instance.
    result['installer.py'] = replace_once(result['installer.py'],
        'shutil.copyfile(payload/name, target)',
        "shutil.copyfile((Path(__file__).resolve().parent if name.endswith('.py') else payload)/name, target)")
    # Honor the target user's uv configuration and index environment variables.
    # System package-manager commands already use the machine's configured sources.
    result['installer.py'] = replace_once(result['installer.py'],
        "UV_PYTHON_INSTALL_DIR=str(root/'python'), UV_NO_CONFIG='1',",
        "UV_PYTHON_INSTALL_DIR=str(root/'python'),")
    result['install_support.py'] = replace_once(result['install_support.py'],
        'label_size = 8', 'label_size = 12')
    return result


def render():
    source = (HERE/'install.sh').read_text()
    shell, python = source.split("<<'PY'\n", 1)
    python, tail = python.rsplit('\nPY\n', 1)
    shell = replace_once(shell,
        '请先通过系统包管理器安装 Python 3.10+，然后重新运行安装器。',
        'Install Python 3.10+ using your system package manager, then run the installer again.')
    shell = replace_once(shell, '# Semantic bootstrap.',
        '# Generated by build_english_installer.py; do not edit this file directly.\n# Semantic bootstrap.')
    shell = replace_once(shell, '# OSS base: https://insightos-artifacts.oss-cn-shanghai.aliyuncs.com/semantic', '# Default downloads: verified GitHub Releases and pinned GitHub LFS assets.')
    python = replace_once(python,
        "print('默认 OSS: https://insightos-artifacts.oss-cn-shanghai.aliyuncs.com/semantic；私有制品请使用 --ticket。')",
        "print('Public snapshot: no default binary channel. Supply an approved --package or --base-url.')")
    python = translate(python)
    python = replace_once(python,
        "'); private OSS requires a valid --ticket. Regenerate expired tickets.'",
        "'); check connectivity to the selected download host and any explicitly supplied ticket.'")
    python = replace_once(python,
        "p.add_argument('--base-url', default=os.environ.get('SEMANTIC_DOWNLOAD_BASE', 'https://insightos-artifacts.oss-cn-shanghai.aliyuncs.com/semantic'))",
        "p.add_argument('--base-url', default='')")
    python = replace_once(python,
        "if not a.package and not a.base_url and not a.ticket:\n    raise SystemExit('Specify a release server with --base-url or a local archive with --package.')\n", '')
    python = replace_once(python,
        "print('Public snapshot: no default binary channel. Supply an approved --package or --base-url.')",
        "print('Default: GitHub Release v0.1.0; --version selects a tag. Missing models use pinned GitHub LFS objects.')\n    print('Dependencies use your configured system/uv package sources; repository and index settings are not rewritten.')")
    python = replace_once(python,
        "print('Semantic: --base-url HTTPS_URL [--version VERSION] | --package FILE [--sha256 HASH]')",
        "print('Semantic: [--version VERSION] | --base-url HTTPS_URL | --package FILE [--sha256 HASH]')")
    python = replace_once(python,
        "explicit_base = any(arg == '--base-url' or arg.startswith('--base-url=') for arg in arguments)",
        "explicit_base = any(arg == '--base-url' or arg.startswith('--base-url=') for arg in arguments)\nif a.source == 'oss' and not a.base_url:\n    a.base_url = 'https://insightos-artifacts.oss-cn-shanghai.aliyuncs.com/semantic'")
    marker = "    status('[OK] Extracted; starting '"
    if marker not in python:
        raise ValueError('Review English extraction integration')
    python = replace_once(python, marker,
        "    restored = hydrate_github_assets(payload, download)\n    if restored:\n        status(f'[OK] Restored {restored} verified GitHub asset files')\n"+marker)
    modules = manager_sources()
    block = ["    # English manager is shipped with this trusted HTTPS bootstrap, not injected into the payload.",
             "    manager_sources = {"]
    for name, content in modules.items():
        block.append('        '+repr(name)+': (')
        block.extend('            '+repr(line) for line in content.splitlines(keepends=True))
        block.append('        ),')
    block.extend(['    }', "    manager = work/'english-manager'", '    manager.mkdir()',
                  '    for name, content in manager_sources.items():',
                  "        (manager/name).write_text(content, encoding='utf-8')"])
    original = "    result = subprocess.run([sys.executable, '-B', str(payload/'installer.py'),"
    python = replace_once(python, original,
        '\n'.join(block)+"\n    result = subprocess.run([sys.executable, '-B', str(manager/'installer.py'),")
    ast.parse(python)
    return shell+"<<'PY'\n"+python+'\nPY\n'+tail


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if the committed English script is out of date')
    args = parser.parse_args()
    expected = render()
    target = HERE/'install-en.sh'
    if args.check:
        if not target.exists() or target.read_text() != expected:
            raise SystemExit('install-en.sh is stale; run python artifacts/build_english_installer.py')
    else:
        target.write_text(expected)
        target.chmod(0o755)


if __name__ == '__main__':
    main()
